### ISSUE TITLE
Add a template and overhaul the website

### ISSUE THREAD

**Issue by A1X5H04** [imhardikdesai/Resume-Builder#1]
I would like to upgrade the UI and UX while also providing some resume templates and also make the template good in UI and UX...
If you want I'll start working on that!

**Comment by imhardikdesai** [comment]
@A1X5H04 if you want to start working on it then it will be great 👍. I will assign this issue.
Thank you 👍😊

**Comment by A1X5H04** [comment]
> @A1X5H04 if you want to start working on it then it will be great 👍. I will assign this issue. Thank you 👍😊

Great!
Thank you!
